### ISSUE TITLE
C/C++ compatibility?

### ISSUE THREAD

**Issue by pseewald** [aradi/fypp#4]
I wonder whether fypp can be used for C/C++ if it is invoked with `--no-folding`. The reason I'm asking this is not because I think it's a good idea to use fypp in C/C++ projects, but it may come in handy to write C bindings to Fortran code that is written using Fypp macros.

**Comment by aradi** [comment]
There should be no problems. The syntax of fypp is specific enough to not to collide with anything in a regular C/C++ code. And its output is language agnostic apart of the folding.
